apiVersion: v2
description: Kolibri Studio, the Content Curation tool for Kolibri!
name: studio
version: 0.3.0
dependencies:
  - name: cloudsql-proxy
    version: 2.0.0
    repository: https://storage.googleapis.com/t3n-helm-charts
    enabled: true
