# Deploy probers only in production environment.
{{- if .Values.productionIngress -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "studio.fullname" . }}-prober-newrelic
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prober-newrelic
            image: {{ .Values.studioProber.imageName }}
            command: ["python", "/deploy/send_metrics_newrelic.py"]
            env:
            - name: PROBER_METRICS_URL
              value: http://{{ template "studio.fullname" . }}-prober-service/metrics
            - name: COMMIT_SHA
              value: {{ .Values.studioApp.releaseCommit }}
            - name: PROBER_NEWRELIC_KEY
              valueFrom:
                secretKeyRef:
                  key: newrelic-key
                  name: {{ template "studio.fullname" . }}
            - name: PROBER_NEWRELIC_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  key: newrelic-account-id
                  name: {{ template "studio.fullname" . }}
          restartPolicy: OnFailure
{{- end }}
