---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "studio.fullname" . }}
  labels:
    tier: app
    app: {{ template "studio.fullname" . }}
spec:
  replicas: {{ .Values.studioApp.replicas }}
  template:
    metadata:
      annotations:
        checksum: {{ include (print $.Template.BasePath "/studio-secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "studio.fullname" . }}
        tier: app
    spec:
      containers:
      - name: app
        image: {{ .Values.studioApp.imageName }}
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}
        - name: STATICFILES_DIR
          value: /app/contentworkshop_static/
        - name: SEND_USER_ACTIVATION_NOTIFICATION_EMAIL
          value: "true"
        # liveness probes are checks for when a pod should be restarted.
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.studioApp.appPort }}
          initialDelaySeconds: 120
          periodSeconds: 5
          # fail 10 times before we restart the pod
          failureThreshold: 10
        ports:
        - containerPort: {{ .Values.studioApp.appPort }}
        # readiness probes are checks for when the pod is ready to serve traffic.
        # Note that this runs even after a pod is Ready. Reaching the failure threshold
        # means the pod is taken off the routing rules, but then once it's passing
        # queries, it's allowed to serve traffic once more.
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.studioApp.appPort }}
          # start pinging for readiness at the 5 second mark.
          # Once it passes, add it to the routing table
          initialDelaySeconds: 5
          # Query every 2 seconds for readiness
          periodSeconds: 2
          # fail 3 times before taking this app off the routing table
          failureThreshold: 3
        volumeMounts:
        - mountPath: /app/contentworkshop_static/
          name: staticfiles
        {{ include "studio.pvc.gcs-creds" . | nindent 8 }}
        {{ include "studio.pvc.gdrive-creds" . | nindent 8 }}
        resources:
          requests:
            cpu: 0.5
            memory: 2Gi
          limits:
            cpu: 0.5
            memory: 2Gi
      - name: nginx-proxy
        image: {{ .Values.studioNginx.imageName }}
        env:
        {{ if .Values.minio.externalGoogleCloudStorage.enabled }}
        - name: AWS_S3_ENDPOINT_URL
          value: https://storage.googleapis.com
        {{ else }}
        - name: AWS_S3_ENDPOINT_URL
          value: {{ template "minio.url" . }}
        {{ end }}
        - name: AWS_BUCKET_NAME
          value: {{ .Values.bucketName }}
        ports:
        - containerPort: {{ .Values.studioNginx.port }}
        volumeMounts:
        - mountPath: /app/contentworkshop_static/
          name: staticfiles
      initContainers:
      - name: db-migrate
        image: {{ .Values.studioApp.imageName }}
        command:
          - make
          - migrate
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}
        volumeMounts: {{ include "studio.pvc.gcs-creds" . | nindent 10 }}
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 2Gi
      volumes:
        - emptyDir: {}
          name: staticfiles
        {{ include "studio.volume.gcs-creds" . | nindent 8 }}
        {{ include "studio.volume.gdrive-creds" . | nindent 8 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{template "studio.fullname" . }}-workers
spec:
  replicas: {{ .Values.studioWorkers.replicas }}
  template:
    metadata:
      labels:
        app: {{template "studio.fullname" . }}-workers
        tier: workers
    spec:
      volumes:
        {{ include "studio.volume.gcs-creds" . | nindent 8 }}
      containers:
      - name: worker
        image: {{ .Values.studioApp.imageName }}
        command:
        - make
        - prodceleryworkers
        volumeMounts:
        {{ include "studio.pvc.gcs-creds" . | nindent 10 }}
        env: {{ include "studio.sharedEnvs" . | nindent 10 }}
        resources:
          requests:
            cpu: 0.5
            memory: 2Gi
          limits:
            cpu: 0.5
            memory: 2Gi
