---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "studio.fullname" . }}
  labels:
    tier: app
    app: {{ template "studio.fullname" . }}
spec:
  replicas: {{ .Values.studioApp.replicas }}
  selector:
    matchLabels:
      app: {{ template "studio.fullname" . }}
      tier: frontend
  template:
    metadata:
      annotations:
        checksum: {{ include (print $.Template.BasePath "/job-template.yaml") . | sha256sum }}
      labels:
        app: {{ template "studio.fullname" . }}
        tier: frontend
    spec:
      initContainers:
      - name: collectstatic
        image: {{ .Values.studioApp.imageName }}
        workingDir: /contentcuration/
        command:
        - make
        args:
        - collectstatic
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: contentcuration.collectstatic_settings
        - name: STATICFILES_DIR
          value: /app/contentworkshop_static/
        volumeMounts:
        - mountPath: /app/contentworkshop_static/
          name: staticfiles
      containers:
      - name: app
        image: {{ .Values.studioApp.imageName }}
        workingDir: /contentcuration/contentcuration/
        command:
        - gunicorn
        args:
        - contentcuration.wsgi:application
        - --timeout=4000
        - --workers=2
        - --bind=0.0.0.0:{{ .Values.studioApp.appPort }}
        - --pid=/tmp/contentcuration.pid
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}
        - name: SEND_USER_ACTIVATION_NOTIFICATION_EMAIL
          value: "true"
        - name: DATA_DB_HOST
          value: {{ template "cloudsql-proxy.fullname" . }}
        - name: GOOGLE_CLOUD_STORAGE_SERVICE_ACCOUNT_CREDENTIALS
          value: /var/secrets/gcs-writer-service-account-key.json
        ports:
        - containerPort: {{ .Values.studioApp.appPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.studioApp.appPort }}
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: 0.5
            memory: 2Gi
          limits:
            memory: 2Gi
        volumeMounts:
          - mountPath: /var/secrets
            name: gcs-writer-service-account-key
            readOnly: true
      - name: nginx-proxy
        image: {{ .Values.studioNginx.imageName }}
        env:
        - name: AWS_S3_ENDPOINT_URL
          value: https://storage.googleapis.com
        - name: AWS_BUCKET_NAME
          value: {{ .Values.studioApp.gcs.bucketName }}
        ports:
        - containerPort: {{ .Values.studioNginx.port }}
        volumeMounts:
        - mountPath: /app/contentworkshop_static/
          name: staticfiles
        resources:
          requests:
            cpu: 0.2
            memory: 256Mi
          limits:
            memory: 512Mi
      volumes:
        - emptyDir: {}
          name: staticfiles
        - name: gcs-writer-service-account-key
          secret:
            secretName: {{ template "studio.fullname" . }}
            items:
            - key: gcs-writer-service-account-key
              path: gcs-writer-service-account-key.json
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: full-gcp-access-scope
                operator: In
                values:
                - "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{template "studio.fullname" . }}-workers
spec:
  replicas: {{ .Values.studioWorkers.replicas }}
  selector:
    matchLabels:
      app: {{ template "studio.fullname" . }}-workers
      tier: workers
  template:
    metadata:
      labels:
        app: {{ template "studio.fullname" . }}-workers
        tier: workers
    spec:
      containers:
      - name: worker
        image: {{ .Values.studioApp.imageName }}
        command:
        - make
        {{- if not .Values.productionIngress }}
        - setup
        {{- end }}
        - prodceleryworkers
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}
        - name: DATA_DB_HOST
          value: {{ template "cloudsql-proxy.fullname" . }}
        resources:
          requests:
            cpu: 0.5
            memory: 2Gi
          limits:
            cpu: 2
            memory: 8Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: full-gcp-access-scope
                operator: In
                values:
                - "true"
