name: Send reply on a new contributor pull request
on:
  pull_request_target:
    types: [opened]
jobs:
  call-workflow:
    name: Call shared workflow
    uses: learningequality/.github/.github/workflows/contributor-pr-reply.yml@main
    secrets:
      LE_BOT_APP_ID: ${{ secrets.LE_BOT_APP_ID }}
      LE_BOT_PRIVATE_KEY: ${{ secrets.LE_BOT_PRIVATE_KEY }}
      SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL: ${{ secrets.SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL }}
